spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skillbox_blog?serverTimezone=Asia/Vladivostok
    username: root
    password: testtest
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

blog:
  title: DevPub
  subtitle: 'Рассказы разработчиков'
  phone: '+7 913 000-00-00'
  email: kostnab1991@gmail.com
  copyright: 'Константин Набоков'
  copyrightFrom: 2021
